<?php 
class eventclass_feedback  extends eventsBase
{ 
	function eventclass_feedback()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


//	onscreen events


	}
// Captchas functions	

//	handlers

		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values,&$keys,$inline,&$pageObject)
{

		
//SCRIPT TO SSEND EMAIL FOR USER APPROVAL
//send email notification

		$to2 ='kopiaman@yahoo.com';
		$subject2 ="E-Movement Feedback  ";
		$headers2 ="From: E-Movement Sytem <no-reply@emovement.bptv.com> \r\n";
		$headers2 .="Content-type: text/html" ."\r\n";

		$link="http://ihijrah.com/emovement";

		$message2 ="<html><body>
		<p> Hi admin, please check the feedback below. </p>
		<p><strong>Title: </stong> $values[title] <br>
    <strong>Category: </stong> $values[categories] <br>
    <strong>Feedback: </stong> $values[feedback] <br>

		<p style='font-size:11px'> **Note: This is automatic notification generated by system***</p> 
		</body></html>";
		//jika sambungan internet ada sent email 
		$whitelist = array('127.0.0.1', "::1");
		if(!in_array($_SERVER['REMOTE_ADDR'], $whitelist)){
			 $mailto=mail($to2, $subject2, $message2, $headers2);
		}else{};	


;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
//	onscreen events

} 
?>
