<?php 
class eventclass_timetable  extends eventsBase
{ 
	function eventclass_timetable()
	{
	// fill list of events
		$this->events["AfterAdd"]=true;


		$this->events["IsRecordEditable"]=true;

		$this->events["AfterEdit"]=true;


//	onscreen events


	}
// Captchas functions	

//	handlers

		
		
		
		
		
		
		
		
		
		
		
				// After record added
function AfterAdd(&$values,&$keys,$inline,&$pageObject)
{

		global $conn;
$id=$keys['id'];
$start_time=$values['start_time'];
$end_time=$values['end_time'];
$sdate=$values['date'];
$edate=$values['endate'];
$category=$values['category'];

$userid=$_SESSION['userid'];
$pos=$_SESSION['pos'];$department=$_SESSION['department'];$leaderpos=$_SESSION['pos']+10;
$sub=$_SESSION['subdepartment'];

$sql_up= "UPDATE timetable SET staffID='$userid',department='$department',subdepartment='$sub',pos='$pos' WHERE id='$id'";
$query_up=db_exec($sql_up,$conn);

while(strtotime($sdate)<strtotime($edate)) {
$sdate=date("Y-m-d", strtotime("+1 day", strtotime($sdate)));
$sql_1= "INSERT INTO timetable (fid,start_time,end_time,staffID,date,category,title,level,location,organizer,department,subdepartment,pos,sstatus,summary,attachment) 
values ('$id','$start_time','$end_time','$userid','$sdate','$category','$values[title]','$values[level]','$values[location]','$values[organizer]','$_SESSION[department]','$sub','$_SESSION[pos]','$values[sstatus]','$values[summary]','$values[attachment]')";
db_exec($sql_1,$conn);
};

//email user
$sql_umail= "SELECT umail AS umail,fullname FROM user WHERE id='$userid'";
$query_umail=db_query($sql_umail,$conn);
$row_umail=db_fetch_array($query_umail);
$usermail=$row_umail['umail'];
$fullname=$row_umail['fullname'];

//leader information
if($pos==10){
//send email to KPP yang sama sub department
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='20' AND subdepartment='$sub' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else if($pos==20){
//send email to timbalan department yang sama
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='30' AND department='$department' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else if($pos==30){ 
 //send email to pengarah 
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='40' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else{}


$to2 =$leaderemail;

$sdate2=date("d-m-Y", strtotime($values['date']));
if($values['endate']){
$endate2=date("d-m-Y", strtotime($values['endate']));
}else{  $endate2=''; };

$stime2=date("H:i", strtotime($start_time)); 
if($end_time){
$etime2=date("H:i", strtotime($end_time)); 
}else{ $etime2=''; }

$subject2 ="New E-Movement Application : $values[title] - Pending ";
$headers2 ="From: $fullname < ". $usermail ."> \r\n";
$headers2 .="CC: $fullname < ". $usermail ."> \r\n";
$headers2 .= "Content-type: text/html" ."\r\n";

$link="http://ihijrah.com/emovement";

$message2 ="<html><body>
<p><strong> Title:  $values[title] </strong> </p><br ><br> 
<p> Category   :  $values[category]  </p>
<p> Title      :  $values[title]  </p>
<p> Level      :  $values[level]  </p>
<p> Location   :  $values[location]  </p>
<p> Organizer  :  $values[organizer]  </p>
<p> Date       :  $sdate2 ~ $endate2  </p>
<p> Time       :  $stime2 ~ $etime2  </p><br > 
<p> Summary    :  $values[summary]  </p>

<p> For leaders, Please login To Approve/Reject This Application . <br>
Go to E-Movement System <a href='$link' target='_blank' > HERE</a></p>  <br>

<p style='font-size:11px'> **Note: This is automatic notification generated by system***</p> 
</body></html>";


//jika sambungan internet ada sent email 
$whitelist = array('127.0.0.1', "::1");
if(!in_array($_SERVER['REMOTE_ADDR'], $whitelist)){
    $mailto=mail($to2, $subject2, $message2, $headers2);
}else{};	



;		
} // function AfterAdd

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// Is Record Editable
function IsRecordEditable(&$values,$isEditable)
{

		

// Place event code here.
// Use "Add Action" button to add code snippets.

if($values['staffID']!=$_SESSION['userid']){

return true;
}else{
return false;
};
;		
} // function IsRecordEditable

		
		
		
		
		
		
		
		

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
				// After record updated
function AfterEdit(&$values,$where,&$oldvalues,&$keys,$inline,&$pageObject)
{

		
global $conn;
$status=$values['sstatus'];
$fid=$keys['id'];
$start_time=$values['start_time'];
$end_time=$values['end_time'];
$sdate=$values['date'];
$edate=$values['endate'];
$category=$values['category'];

$userid=$values['staffID'];
$pos=$values['pos'];
$department=$values['department'];
$sub=$values['subdepartment'];

$update=date("Y-m-d H:i:s");

//update for same event at another erow
if($status=='Approved' ){
	$sql_up= "UPDATE timetable SET sstatus ='$status',date_status='$update' WHERE fid='$fid' OR id='$fid' ";
	$query_up=db_exec($sql_up,$conn);
}else if($status=='Rejected'){
	$sql_up= "UPDATE timetable SET sstatus ='$status',date_status='$update' WHERE fid='$fid' OR id='$fid' ";
	$query_up=db_exec($sql_up,$conn);
}else{};

// user information
$sql_umail= "SELECT umail AS umail,fullname FROM user WHERE id='$userid'";
$query_umail=db_query($sql_umail,$conn);
$row_umail=db_fetch_array($query_umail);
$usermail=$row_umail['umail'];
$fullname=$row_umail['fullname'];

//leader information
if($pos==10){
//send email to KPP yang sama sub department
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='20' AND subdepartment='$sub' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else if($pos==20){
//send email to timbalan department yang sama
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='30' AND department='$department' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else if($pos==30){ 
 //send email to pengarah 
$sql_lmail= "SELECT umail AS lemail FROM user WHERE pos='40' AND sstatus='Active'";
$query_lmail=db_query($sql_lmail,$conn);
$row_lmail=db_fetch_array($query_lmail);
$leaderemail=$row_lmail['lemail'];
}else{}

$to2 =$usermail;

$sdate2=date("d-m-Y", strtotime($values['date']));
if($values['endate']){
$endate2=date("d-m-Y", strtotime($values['endate']));
}else{  $endate2=''; };


$stime2=date("H:i", strtotime($start_time)); 
if($end_time){
$etime2=date("H:i", strtotime($end_time)); 
}else{ $etime2=''; }

$subject2 ="E-Movement Status : $values[title]- $status";
$headers2 ="From: $fullname < ". $leaderemail ."> \r\n";
$headers2 .= "Content-type: text/html" ."\r\n";

$link="http://ihijrah.com/emovement";

$message2 ="<html><body>
<p><strong> Title:  $values[title]  </strong> </p>
<p> Category   :  $values[category]  </p>
<p> Title      :  $values[title]  </p>
<p> Level      :  $values[level]  </p>
<p> Location   :  $values[location]  </p>
<p> Organizer  :  $values[organizer]  </p>
<p> Date       :  $sdate2 ~ $endate2  </p>
<p> Time       :  $stime2 ~ $etime2  </p>
<p> Note       :  $values[note]  </p><br > 
<p> Summary    :  $values[summary]  </p><br><br>

<p style='font-size:11px'> **Note: This is automatic notification generated by system***</p> 
</body></html>";



//jika sambungan internet ada sent email 
$whitelist = array('127.0.0.1', "::1");
if(!in_array($_SERVER['REMOTE_ADDR'], $whitelist)){
    $mailto=mail($to2, $subject2, $message2, $headers2);
}else{};	

;		
} // function AfterEdit

		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
		
//	onscreen events

} 
?>
